HOMEPAGE = "https://www.homepath.com/listings/"
LAST_ELEMENT = -1
FULL_EXTENSTION = 3
HALF_URL = -15
HOST = 'localhost'
USER = 'root'
PASS = 'Uiop7890'
DB_FILENAME = 'usa_scraping_database'
DB_PATH = r'C:\Users\liat grinberg\Desktop\Ohad\ITC course\usa_real_estate_scraping'
WEBDRIVER_PATH = r"C:\Users\ronle\Documents\the_webdriver\chromedriver.exe"